from __future__ import annotations

# Gap candidates. Shown only if missing from claims.

GAPS = [
    {
        "prompt_ja": "見る",
        "prompt_hint": "て-форма",
        "expected": "見て",
        "gloss_ru": "смотреть → 見て",
        "reason": "Рядом с 行く / て-формой",
        "tags": "te-form",
    },
    {
        "prompt_ja": "来る",
        "prompt_hint": "て-форма",
        "expected": "来て",
        "gloss_ru": "приходить → 来て",
        "reason": "Рядом с 行く / て-формой",
        "tags": "te-form",
    },
    {
        "prompt_ja": "する",
        "prompt_hint": "て-форма",
        "expected": "して",
        "gloss_ru": "делать → して",
        "reason": "Рядом с て-формой",
        "tags": "te-form",
    },
    {
        "prompt_ja": "プレゼント",
        "prompt_hint": "когда даёте вы, не くれる",
        "expected": "あげる",
        "gloss_ru": "От меня / нас. Пара к くれる",
        "reason": "Пара к くれる",
        "tags": "give",
    },
    {
        "prompt_ja": "手紙",
        "prompt_hint": "получить (я — получатель)",
        "expected": "もらう",
        "gloss_ru": "Я получаю. Не путать с くれる",
        "reason": "Триада あげる / くれる / もらう",
        "tags": "give",
    },
    {
        "prompt_ja": "読む",
        "prompt_hint": "ない-форма",
        "expected": "読まない",
        "gloss_ru": "u-глагол: む → まない",
        "reason": "Рядом с 食べない",
        "tags": "nai",
    },
    {
        "prompt_ja": "書く",
        "prompt_hint": "потенциал",
        "expected": "書ける",
        "gloss_ru": "писать → мочь писать",
        "reason": "Рядом с 読める",
        "tags": "potential",
    },
    {
        "prompt_ja": "寒い",
        "prompt_hint": "причина, мягче から",
        "expected": "寒いので",
        "gloss_ru": "Потому что (мягко). На уроке мог быть から",
        "reason": "Пара к から",
        "tags": "reason",
    },
    {
        "prompt_ja": "宿題",
        "prompt_hint": "ещё не / всё ещё",
        "expected": "まだ",
        "gloss_ru": "Пара к もう",
        "reason": "Пара к もう",
        "tags": "mou",
    },
    {
        "prompt_ja": "本",
        "prompt_hint": "счётный суффикс для книг",
        "expected": "冊",
        "gloss_ru": "一冊、二冊。 Не 本 (длинные предметы)",
        "reason": "Рядом со счётом 本",
        "tags": "counter",
    },
    {
        "prompt_ja": "飲む",
        "prompt_hint": "вежливое хотение",
        "expected": "飲みたいです",
        "gloss_ru": "たいです после глагола",
        "reason": "Рядом с たい",
        "tags": "tai",
    },
    {
        "prompt_ja": "食べる",
        "prompt_hint": "состояние после て",
        "expected": "食べている",
        "gloss_ru": "Результат или процесс. На уроке: している",
        "reason": "Рядом с прогрессивом",
        "tags": "teiru",
    },
]
